name: build AppImage
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build AppImage
        run: |
          docker buildx build --output=. .
      - name: Upload AppImage
        uses: actions/upload-artifact@v4
        with:
          name: Qcma-x86_64.AppImage
          path: ${{github.workspace}}/Qcma-x86_64.AppImage
